INSERT INTO POLITIKERE (name,partyShort,partyName,votes) VALUES
('Marcel Meijer',               'A','Socialdemokratiet', 1231),
('Michael Kristensen',          'A','Socialdemokratiet', 323),
('Helle Hansen',                'A','Socialdemokratiet', 234),
('Karina Knobelauch',           'A','Socialdemokratiet', 133),
('Stefan Hafstein Wolffbrandt', 'A','Socialdemokratiet', 123),
('Robert V. Rasmussen','A','Socialdemokratiet', 111),
('Pia Ramsing','A','Socialdemokratiet', 3312),
('Anders Baun Sørensen','A','Socialdemokratiet', 232),
('Per Urban Olsen','C','Det konservative Folkeparti', 653),
('Peter Askjær', 'C','Det konservative Folkeparti', 323),
('Martin Sørensen', 'C','Det konservative Folkeparti', 111),
('Louise Bramstorp', 'C','Det konservative Folkeparti', 32),
('Sigfred Jensen', 'C','Det konservative Folkeparti', 42),
('Jørn C. Nissen', 'C','Det konservative Folkeparti', 53),
('Morten Ø. Kristensen', 'C','Det konservative Folkeparti', 56),
('Susanne Andersen', 'C','Det konservative Folkeparti', 11),
('Iulian V. Paiu', 'C','Det konservative Folkeparti', 1),
('Ulla Holm', 'SF', 'Socialistisk Folkeparti', 243),
('Kjeld Bønkel', 'SF', 'Socialistisk Folkeparti', 555),
('Anne Grethe Olsen', 'SF', 'Socialistisk Folkeparti', 131),
('Lone Krag', 'SF', 'Socialistisk Folkeparti', 23),
('Børge S. Buur', 'SF', 'Socialistisk Folkeparti', 145),
('Per Mortensen', 'O', 'Dansk Folkeparti', 300),
('Søren Wiese', 'V', 'Venstre, Danmarks Liberale Parti', 412),
('Anita Elgaard Højholt Olesen','V', 'Venstre, Danmarks Liberale Parti', 321),
('Carsten Bruun', 'V', 'Venstre, Danmarks Liberale Parti', 232),
('Mogens Exner', 'V', 'Venstre, Danmarks Liberale Parti', 451),
('Anja Guldborg', 'V', 'Venstre, Danmarks Liberale Parti', 13),
('Klaus Holdorf', 'V', 'Venstre, Danmarks Liberale Parti', 233),
('Katrine Høegh Mc Quaid', 'Ø', 'Enhedslisten + De Rød Grønne', 414),
('Jette M. Søgaard', 'Ø', 'Enhedslisten + De Rød Grønne', 22),
('Søren Caspersen', 'Ø', 'Enhedslisten + De Rød Grønne', 32),
('Pia Birkmand', 'Ø', 'Enhedslisten + De Rød Grønne', 441);